### ISSUE TITLE
What were the specs for the machine used to train this?

### ISSUE THREAD

**Issue by jake-g** [yongxuUSTC/dcase2017_task4_cvssp#3]
I'm trying to tweak the model to run on my workstation with two titan 12gb gpus. Any suggestions?

**Comment by qiuqiangkong** [comment]
Hi Jake,


    Many thanks for your interest!


    We run our code on one TitanX GPU with 12 Gb memory. We have not tried running it on two GPUs yet. I think you may use 2 GPUs by switching to tensorflow backend. Tensorflow is able to do multi-GPU running.


    Please let us know if there is any questions.


Best wishes,


Qiuqiang

________________________________

**Comment by jake-g** [comment]
Using one gpu fixed my issue!
