### ISSUE TITLE
runme.sh dies with "No such file or directory: preds/crnn_sed/at_prob_mat.csv.gz"

### ISSUE THREAD

**Issue by Jane222** [yongxuUSTC/dcase2017_task4_cvssp#4]
Hello, every time I try to execute `runme.sh` the script dies on me after a couple of hours with

`Traceback (most recent call last):
  File "main_crnn_sed.py", line 306, in <module>
    get_stat(args, at_bool=True, sed_bool=True)
  File "main_crnn_sed.py", line 232, in get_stat
    thres_ary=thres_ary)
  File "/data/docker_share/video_surveillance/Sound_Classification/Google_AudioSet/dcase2017_task4_cvssp/evaluation/evaluate.py", line 49, in get_stats_from_prob_mat_csv
    (pd_na_list, pd_prob_mat) = at_read_prob_mat_csv(pd_prob_mat_csv)
  File "/data/docker_share/video_surveillance/Sound_Classification/Google_AudioSet/dcase2017_task4_cvssp/evaluation/io_task4.py", line 64, in at_read_prob_mat_csv
    with my_open(prob_mat_path, 'rb') as f_read:
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/data/docker_share/video_surveillance/Sound_Classification/Google_AudioSet/dcase2017_task4_cvssp/preds/crnn_sed/at_prob_mat.csv.gz'`

An pointers on why this is or how to fix it?

Thanks!

**Comment by qiuqiangkong** [comment]
Hello,


    Many thanks for the interest!


    That means the file is not created.


    Please check if train & recognize is complete.


     Maybe try run the recognition line in .runme.sh again and see if the file is created?


Best wishes,

Qiuqiang

________________________________

**Comment by Jane222** [comment]
Hello Qiuqiang, thanks for your fast response!

The scaler part works (both `training.h5` and `training.scaler` are created, as well as `testing.h5` and `evaluation.h5`) but the directory `models` never gets created, so I assume the Train SED part never runs through. The only error message I get is the one posted above. How could I figure this out / debug it further?

Thanks for your help!

**Comment by qiuqiangkong** [comment]
Hi,


    Many thanks! There is a bug in creating the path for calculate scaler. We have fixed it!


    If you check out the latest version and run from calculate scaler again, it should work. If not, please let us know without hesitation!


Best wishes,


Qiuqiang




________________________________

**Comment by Jane222** [comment]
Thanks, it runs through without any errors now!:-)
Closing this issue.
