### ISSUE TITLE
Purpose of the scaler and other pre-processing steps for inference?

### ISSUE THREAD

**Issue by Jane222** [yongxuUSTC/dcase2017_task4_cvssp#5]
Hello,
I was wondering how important the scaler is and how to use it... Say I'd like to run inference on a group consisting of ten .wav files - should I use the scaler on them that I computed from these 10 files, or rather the scaler that was computed from the whole training set of the DCASE2017 Task 4 challenge?

Thank you!

**Comment by qiuqiangkong** [comment]
Hi, 

    In the training, we observe using scaler will speed up training a lot. 

    To use the scaler, please see here https://github.com/yongxuUSTC/dcase2017_task4_cvssp/blob/master/main_crnn_sed.py#L80

    Please let us know if there is any questions without hesitation! 

Best wishes, 

Qiuqiang

**Comment by Jane222** [comment]
Thanks once again for your fast response.

The reason I was asking is that I'm trying to figure out the most efficient way to use the fully trained model to run inference on a single arbitrary .wav file that I provide.

Apparently, a .wav file cannot be passed to the trained model directly, the features need to be extracted first... So what I ended up doing is the following using a bash script:

```python2 prepare_data.py extract_features --wav_dir="$wav_dir" --out_dir="$features_dir" --recompute=True

python2 prepare_data.py pack_features --fe_dir="$features_dir" --csv_path="" --out_path="$hdf5_features"

python2 prepare_data.py calculate_scaler --hdf5_path="$hdf5_features" --out_path="$scaler"

python2 dcase_inference_helper.py --hdf5_features="$hdf5_features" --scaler="$scaler" --model="$model" --out_file="$out_file"
```

where `dcase_inference_helper.py` basically contains:

```
(x, y, na_list) = load_hdf5_data(args.hdf5_features, verbose=1)

x = do_scale(x, args.scaler, verbose=1)

model = load_model(args.model)

pred = model.predict(x)
```
But I was wondering if all those steps are necessary. You wrote that using the scaler will speed up training a lot - what about inference? Will it speed up inference as well? Does it have to be used during inference at all, or is the `do_scale()` call in my `dcase_inference_helper.py` completely unnecessary?

If using the scaler for inference is necessary: Note that I computed the scaler from the single `.wav` file in the `$wav_dir` directory. Should I have used the scaler that was computed on the whole DCASE2017 Task4 training dataset instead?

Also, is `prepare_data.py pack_features` something that I should execute as well? Seems that packing the features into a hdf5 file just to load them from that file again to feed them to the model is an intermediate step that could be omitted to speed things up... Is that correct or are there benefits from using the intermediate hdf5 when classifying (inferring) a single .wav file?

Is there something else that could be improved that I'm overlooking?

Thank you so much!

**Comment by qiuqiangkong** [comment]
Hi Jana,


   The inference part you write is right.


   For a new .wav file, You need to extract its log Mel spectrogram feature first. You may use some code from here to extract feature: (https://github.com/yongxuUSTC/dcase2017_task4_cvssp/blob/master/prepare_data.py#L43)


   As scaler is used in the training, you MUST use scaler in the recognition as well. Please note the scaler is not calculated from the testing data, but from the training data. That is you should use the scaler that was computed on the whole DCASE2017 Task4 training dataset. Then you may do:

x = do_scale(x, args.scaler, verbose=1)

   Then you may do:

model = load_model(args.model)

pred = model.predict(x)

   to do recognition.

You do not need to pack feature in your case. Pack features to hdf5 files are just used to speed up loading files. It is not necessary.

   Hope it helps! Please let use know if there are any questions without hesitation.

Best wishes,

Qiuqiang

________________________________

**Comment by Jane222** [comment]
Hello Qiuqiang,

I've now removed the saving-to-hdf5 step completely and managed to speed up the inference by about 20 % (The mel features that have been saved to disk are now being loaded as a numpy array and do_scale() is being called on this numpy array directly).

But there's still a lot of overhead when doing inference on a single .wav (it takes about 16 seconds for a single .wav and about 18 seconds for a batch of 10 .wavs). I guess I can try to skip saving the mel features to disk and feed them directly to the scaler instead... Will post here if it speeds things up.

**Comment by qiuqiangkong** [comment]
Hello Jane, 

    Many thanks for the insights! Yes I think the inference can be speed up in a batch way. 

Qiuqiang

**Comment by Jane222** [comment]
Hello Qiuqiang,

I've finally ended up profiling the python scripts and behold, about 90% of the runtime was needed just to load the Keras model.
So if you want to run inference in a loop for wav files coming in in an online fashion, running inference doesn't take longer than a few seconds per wav file, even without GPU acceleration.
So the other pre-processing steps aren't that expensive after all.

That answers all my questions, closing this issue now.

Thanks for your help!
