### ISSUE TITLE
License for the code?

### ISSUE THREAD

**Issue by Jane222** [yongxuUSTC/dcase2017_task4_cvssp#6]
Hello,

I really enjoyed playing around with yor code and model.

Could you tell me under which license are you publishing the code in this repository?

Thanks!

**Comment by Jane222** [comment]
That's great, thank you!:-)
Would you mind uploading the license into this repository at some point?

**Comment by qiuqiangkong** [comment]
Hi,


    Many thanks! MIT liscence is pushed!


Best wishes,


Qiuqiang

________________________________

**Comment by Jane222** [comment]
Thank you so much!
Closing this issue now.
